[project]
name = "sample-uv"
version = "0.1.0"
description = "Sample project with UV dependency management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio[mcp]>=5.30.0",
    "huggingface-hub[mcp]>=0.32.0",
    "mcp[cli]>=1.11.0",
]
